version: '3.4'

services:

  dsrproject_postgresql:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=dsrDB
    ports:
      - "25432:5432"
    restart: unless-stopped
    networks:
      - shared_dsrproject_net
    volumes:      
      - ~/.docker-conf/postgresql/data/:/postgresql/data


      
  dsrproject_redis:
    ports:
      - '6379:6379'
    networks:
      - shared_dsrproject_net
    restart: unless-stopped
    volumes:      
      - ~/.docker-conf/redis/data/:/redis/data

  dsrproject_rabbitmq:
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672" 
    networks:
      - shared_dsrproject_net
    volumes:      
      - ~/.docker-conf/redis/data/:/rabbitmq/data


  dsrproject.api:
    ports:
      - "10000:80"
    networks:
      - shared_dsrproject_net
    env_file:
      - env.api
    restart: unless-stopped

  dsrproject.identity:
    ports:
      - "10001:80"
    networks:
      - shared_dsrproject_net
    env_file:
      - env.identity
    restart: unless-stopped

  dsrproject.worker:
    networks:
      - shared_dsrproject_net
    env_file:
      - env.worker

  dsrproject_web:
    ports:
      - "10002:80"
    networks:
      - shared_dsrproject_net

networks:
  shared_dsrproject_net:
    driver: bridge

