version: '3.4'

services:

  #dsrproject_postgresql:
  #  environment:
  #    - POSTGRES_USER=postgres
  #    - POSTGRES_PASSWORD=passw0rd
  #    - POSTGRES_DB=dsrDB
  #  ports:
  #    - "5432:5432"
  #  networks:
  #    - shared_dsrproject_net
  #  volumes:      
  #    - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

      
  dsrproject_redis:
    ports:
      - '6379:6379'
    networks:
      - shared_dsrproject_net
    volumes:      
      - ~/.docker-conf/redis/data/:/data


  dsrproject.api:
    ports:
      - "10000:80"
    networks:
      - shared_dsrproject_net
    env_file:
      - env.api

networks:
  shared_dsrproject_net:
    name: dsr_net_project
    driver: bridge
