version: '3.4'

services:

  dsrproject_postgresql:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=dsrDB
    ports:
      - "5432:5432"

    restart: unless-stopped
    networks:
      - shared_dsrproject_net

      
  dsrproject_redis:
    ports:
      - '6379:6379'
    networks:
      - shared_dsrproject_net
    restart: unless-stopped
    volumes:      
      - ~/.docker-conf/redis/data/:/data


  dsrproject.api:
    ports:
      - "10000:80"
    networks:
      - shared_dsrproject_net
    env_file:
      - env.api
    restart: unless-stopped

  dsrproject.identity:
    ports:
      - "10001:80"
    networks:
      - shared_dsrproject_net
    env_file:
      - env.identity
    restart: unless-stopped

networks:
  shared_dsrproject_net:
    driver: bridge
