version: '3.4'

services:

  dsrproject_postgresql:
    image: postgres:latest
    
  dsrproject_redis:
    image: redis

  dsrproject_rabbitmq:
    image: rabbitmq:management

  dsrproject.api:
    image: ${DOCKER_REGISTRY-}dsrprojectapi
    build:
      context: .
      dockerfile: Systems/Api/DsrProject.Api/Dockerfile

    depends_on:
      - dsrproject_postgresql
      - dsrproject_redis
  dsrproject.identity:
    image: ${DOCKER_REGISTRY-}dsrprojectidentity
    build:
      context: .
      dockerfile: Systems/Identity/DsrProject.Identity/Dockerfile

    depends_on:
      - dsrproject_postgresql
      - dsrproject_redis
      - dsrproject.api

  dsrproject.worker:
    image: ${DOCKER_REGISTRY-}dsrprojectworker
    build:
      context: .
      dockerfile: Systems/Workers/DsrProject.Worker/Dockerfile

    depends_on:
      - dsrproject_postgresql
      - dsrproject_redis
      - dsrproject_rabbitmq
      - dsrproject.api